package server.helpers;

import server.helpers.Wordlist;

import java.util.Random;

/**
 * Created by Kim Säther on 09-Nov-18.
 */
public class ArrayWordList implements Wordlist {
    Random random = new Random();

    @Override
    public String getRandomWord() {
        int randomIndex = random.nextInt(words.length);
        return words[randomIndex];
    }

    private static final String[] words = new String[]{
        "Jordnöt",
        "Dillchips",
        "Stjärna",
        "Automatiskt",
        "Toapapper",
        "Kylskåp",
        "Adventsstjärna",
        "Chokladpudding",
        "Zombie",
        "Alfabet",
        "Flod",
        "Plåster",
        "Adjektiv",
        "Brev",
        "Brevlåda",
        "Aktiv",
        "Bibliotekarie",
        "Kamera",
        "Godis",
        "Pannkakssmet",
        "Barnrumpa",
        "Randig",
        "Morgonrock",
        "Badkar",
        "Flugsmällare",
        "Osynlig",
        "Dörr",
        "Persienn",
        "Påskägg",
        "Patient",
        "Passagerare",
        "Soppa",
        "Mojäng",
        "Polkagris",
        "Lärare",
        "Grusplan",
        "Plastglas",
        "Papperslapp",
        "Rap",
        "Visitkort",
        "Hushållspapper",
        "Bil",
        "Fotbollsspelare",
        "Kaka",
        "Chokladboll",
        "Fyrtiotvå",
        "Plåtslagare",
        "Rivjärn",
        "Äpple",
        "Citron",
        "Automatisk",
        "Wellpapp",
        "Gröt",
        "Plånbok",
        "Spela",
        "Internet",
        "Gosedjur",
        "Påskhare",
        "Tivoli",
        "Födelsedag",
        "Omslagspapper",
        "Plastpåse",
        "Flygplats",
        "Snowboard",
        "Karatespark",
        "Lagbrott",
        "Polisbil",
        "Vinterdäck",
        "Apa",
        "Lakrits",
        "Spolarvätska",
        "Julafton",
        "Sommar",
        "Ballonger",
        "Gurka",
        "Dator",
        "Mobiltelefon",
        "Netflix",
        "Fågel",
        "Dinosaurie",
        "Fjärilssim",
        "Chokladpudding",
        "Backe",
        "Flaska",
        "Sortiment",
        "Penna",
        "Rosa",
        "Gul",
        "Musikstudio",
        "Gräsklippare",
        "Whiteboardtavla",
        "Piprensare",
        "Musmatta",
        "Matematikläxa",
        "Kräkpåse",
        "Tallrik",
        "Slajm",
        "Bubbelvatten",
        "Ferrari",
        "Dårhus",
        "Rörtång",
        "Badhus",
        "El",
        "Uggla",
        "Stålmannen",
        "Batman",
        "Nöjesresa",
        "Melodifestivalen",
        "Spya",
        "Usel",
        "Kanonbra",
        "Tomat",
        "Ketchup",
        "Jultomte",
        "Tacos",
        "Svinbra",
        "Katt",
        "Hund",
        "Elefant",
        "Kamel",
        "Isbjörn",
        "Späckhuggare",
        "Vithaj",
        "Sjukhus"
    };
}
